spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/sample?serverTimeZone=UTC&CharacterEncoding=UTF-8
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: gotkdvndfur1!
    hikari:
      maximum-pool-size: 10
      connection-timeout: 5000
      connection-init-sql: SELECT 1
      validation-timeout: 2000
      minimum-idle: 10
      idle-timeout: 600000
      max-lifetime: 1800000
  jpa:
    open-in-view: false
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update