spring:
  # db1
  datasource:
    url: jdbc:mariadb://localhost:3306/sample?serverTimeZone=UTC&CharacterEncoding=UTF-8
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: sinae0417
    hikari:
      maximum-pool-size: 10
      connection-timeout: 5000
      connection-init-sql: SELECT 1
      validation-timeout: 2000
      minimum-idle: 10
      idle-timeout: 600000
      max-lifetime: 1800000
  # db2
  datasource2:
    url: jdbc:mariadb://localhost:3306/sample?serverTimeZone=UTC&CharacterEncoding=UTF-8
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: sinae0417
    hikari:
      maximum-pool-size: 10
      connection-timeout: 5000
      connection-init-sql: SELECT 1
      validation-timeout: 2000
      minimum-idle: 10
      idle-timeout: 600000
      max-lifetime: 1800000
  
  # resource mapping url
  mvc: 
    static-path-pattern: "/**"
    view:
        prifix: "/"

  # file
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      location: C:\\Users\\annes\\Frontend\\Spring\\worksample\\sample\\src\\main\\resources\\upload
  
  # reload static resourses changes directly
  devtools:
    livereload:
      enabled: true
  
  # View Templete Engine
  thymeleaf:
    prefix: classpath:templates/
    suffix: .html
    cache: false
    check-template-location: true
   
#####
 
# slf4j
logging:
    file:
      name: C:\\Users\\annes\\Frontend\\Spring\\worksample\\sample\\src\\main\\resources\\log\\logback.log
      max-size: 500MB
      max-history: 10

# server     
server:
    port: 8090
    servlet:
        session:
            timeout: 30m
            tracking-modes: cookie