spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/sample?serverTimeZone=UTC&CharacterEncoding=UTF-8
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: gotkdvndfur1!
    hikari:
      maximum-pool-size: 10
      connection-timeout: 5000
      connection-init-sql: SELECT 1
      validation-timeout: 2000
      minimum-idle: 10
      idle-timeout: 600000
      max-lifetime: 1800000
      
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      location: C:\\Users\\User\\worksample\\sample\\src\\main\\webapp\\WEB-INF\\upload
  
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp